import { useContext } from "react";
import { Context } from "../../context/Context";
import { assets } from "../../assets/assets";
import "./modals.css";

const Modals = () => {
	const {
		activeModal,
		setActiveModal,
		prevPrompts,
		clearHistory,
		onSent,
		setRecentPrompt,
	} = useContext(Context);

	if (!activeModal) return null;

	const close = () => setActiveModal(null);

	const loadFromHistory = async (prompt) => {
		close();
		setRecentPrompt(prompt);
		await onSent(prompt);
	};

	return (
		<div className="modal-overlay" onClick={close}>
			<div className="modal-box" onClick={(e) => e.stopPropagation()}>
				<div className="modal-header">
					<p>
						{activeModal === "history" && "History"}
						{activeModal === "settings" && "Settings"}
						{activeModal === "help" && "Help desk"}
					</p>
					<span className="modal-close" onClick={close}>
						&times;
					</span>
				</div>

				<div className="modal-body">
					{activeModal === "history" && (
						<>
							{prevPrompts.length === 0 ? (
								<p className="modal-empty">No conversations yet.</p>
							) : (
								<div className="modal-history-list">
									{[...prevPrompts].reverse().map((item, index) => (
										<div
											key={index}
											className="modal-history-entry"
											onClick={() => loadFromHistory(item)}
										>
											<img src={assets.message_icon} alt="" />
											<p>{item}</p>
										</div>
									))}
								</div>
							)}
						</>
					)}

					{activeModal === "settings" && (
						<>
							<div className="modal-setting-row">
								<div>
									<p className="modal-setting-title">Clear conversation history</p>
									<p className="modal-setting-desc">
										Removes all saved prompts from this browser.
									</p>
								</div>
								<button
									className="modal-danger-btn"
									onClick={() => {
										clearHistory();
										close();
									}}
								>
									Clear
								</button>
							</div>
						</>
					)}

					{activeModal === "help" && (
						<>
							<p className="modal-help-text">
								NEXA AI is a chat assistant. Type a question or click a
								suggestion card to get started.
							</p>
							<p className="modal-help-text">
								Responses are generated by an AI model and may occasionally be
								inaccurate — double-check anything important.
							</p>
							<p className="modal-help-text">
								Having trouble? Check that your API key is configured
								correctly in your environment settings.
							</p>
						</>
					)}
				</div>
			</div>
		</div>
	);
};

export default Modals;
